### ISSUE TITLE
PeakInferHiChIP.sh issue 

### ISSUE THREAD

**Issue by emarti88** [ay-lab/FitHiChIP#28]
Hello,

I have been trying to infer the peaks from my HiChIP data set wit the FitHiChIP utility PeakInferHiChIP.sh instead of using standard one. However, I keep running into an error when I run the script.

File containing DE reads: /.../HT-29-1_S1_L008_001_hg38.bwt2pairs.DEPairs
File containing SC reads: /.../HT-29-1_S1_L008_006_hg38.bwt2pairs.SCPairs
File containing RE reads: /.../HT-29-1_S1_L008_030_hg38.bwt2pairs.REPairs
File containing valid pairs: /.../HT-29-1/HT-29-1_S1_L008_017_hg38.bwt2pairs.validPairs
Traceback (most recent call last):
  File "/.../bin/macs2", line 622, in <module>
    main()
  File "/.../bin/macs2", line 56, in main
    from MACS2.callpeak_cmd import run
  File "/.../lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 31, in <module>
    from MACS2.OptValidator import opt_validate
  File "/.../lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "__init__.pxd", line 155, in init MACS2.IO.Parser (MACS2/IO/Parser.c:22630)
ValueError: numpy.dtype has the wrong size, try recompiling

I have omitted some paths for brevity. My concerns:

1. The are many files with DE, SC, and RE pairs and yet only 1 (seemingly random) is echoed. 
2. I checked in the script that validPairs file search prioritizes the allValidPairs file which you get after running step 2 in HiCPro. This file is present in the input directory and yet is not recognized. 
3. The wrong numpy.dtype error may be because of the wrong file input but otherwise not sure. 

Please advise, and thank you!

Eduardo

**Comment by emarti88** [comment]
Reinstalled MACS2 and it worked

Thanks.
Eduardo

**Comment by emarti88** [comment]
Reinstalled MACS2 and it worked

Thanks.
Eduardo
